-- MySQL Script generated by MySQL Workbench
-- Model: Cafayate    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafayate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafayate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cafayate` ;

-- -----------------------------------------------------
-- Table `cafayate`.`comercios_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`comercios_categorias` (
  `id_categoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`roles` (
  `id_rol` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(10) NOT NULL,
  `id_rol` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  INDEX `id_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `cafayate`.`roles` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`comercios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`comercios` (
  `id_comercio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(5000) NOT NULL,
  `reputacion` VARCHAR(45) NOT NULL DEFAULT '0',
  `domicilio` VARCHAR(45) NOT NULL,
  `barrio` VARCHAR(45) NULL DEFAULT NULL,
  `id_categoria` INT NOT NULL DEFAULT '1',
  `id_usuario` INT NULL DEFAULT NULL,
  `horarios` VARCHAR(5000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_comercio`),
  INDEX `comercio_dueno_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `comercio_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `comercio_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `cafayate`.`comercios_categorias` (`id_categoria`),
  CONSTRAINT `comercio_dueno`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cafayate`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`comercios_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`comercios_imagenes` (
  `id_imagen` INT NOT NULL AUTO_INCREMENT,
  `id_comercio` INT NULL DEFAULT NULL,
  `url` VARCHAR(200) NOT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `comercio_imagen_idx` (`id_comercio` ASC) VISIBLE,
  CONSTRAINT `comercio_imagen`
    FOREIGN KEY (`id_comercio`)
    REFERENCES `cafayate`.`comercios` (`id_comercio`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`datos_publicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`datos_publicos` (
  `id` INT NOT NULL,
  `bienvenida` VARCHAR(5000) NULL DEFAULT 'Welcome text',
  `bienvenida_turismo` VARCHAR(5000) NULL DEFAULT NULL,
  `logo` VARCHAR(100) NULL DEFAULT NULL,
  `instagram` VARCHAR(100) NULL DEFAULT NULL,
  `facebook` VARCHAR(100) NULL DEFAULT NULL,
  `whatsapp` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`novedades_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`novedades_categorias` (
  `id_categoria` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`novedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`novedades` (
  `id_novedad` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `fecha` DATE NOT NULL,
  `contenido` VARCHAR(5000) NULL DEFAULT NULL,
  `imagen` VARCHAR(100) NULL DEFAULT NULL,
  `id_categoria` INT NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_novedad`),
  UNIQUE INDEX `id_novedad_UNIQUE` (`id_novedad` ASC) VISIBLE,
  INDEX `novedad_publicador_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `novedad_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `novedad_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `cafayate`.`novedades_categorias` (`id_categoria`),
  CONSTRAINT `novedad_publicador`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cafayate`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cafayate`.`solicitudes_comerciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafayate`.`solicitudes_comerciante` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nombre` VARCHAR(100) NOT NULL,
  `rubro` VARCHAR(100) NOT NULL,
  `domicilio` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_solicitud`),
  UNIQUE INDEX `id_solicitud_UNIQUE` (`id_solicitud` ASC) VISIBLE,
  INDEX `solicitud_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `solicitud_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cafayate`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
